import type { BookingRequest } from "@/lib/booking/types";

const daysAgo = (n: number) => new Date(Date.now() - 86400000 * n).toISOString();

export const MOCK_BOOKING_REQUESTS: BookingRequest[] = [
  {
    id: "mock-1",
    reference: "DAA-8492",
    status: "Under Review",
    internalStatus: "Screening",
    priority: "High",
    assignedEa: "Sarah M.",
    conflictDetected: false,
    form: {
      name: "Amara Okafor",
      organization: "Lagos Business Forum",
      email: "amara@lagosbusinessforum.org",
      phone: "+234 801 234 5678",
      timezone: "WAT (West Africa)",
      engagementType: "Keynote",
      eventTitle: "Leadership in Uncertain Times",
      audienceSize: "500 – 1,000",
      format: "In-person",
      preferredDate: "2026-11-15",
      alternativeDate: "2026-11-22",
      city: "Lagos",
      country: "Nigeria",
      travelDetails: "International flight required. Accommodation provided.",
      budgetRange: "$25,000 – $50,000",
      recordingPermission: "Video recording",
      vipProtocol: "Governor's office reception. Security detail on arrival.",
      termsAgreed: true,
    },
    documents: [
      {
        id: "doc-1",
        name: "Formal_Invitation_Letter.pdf",
        uploadedAt: daysAgo(2),
        category: "Invitation",
      },
    ],
    statusHistory: [
      {
        previousStatus: null,
        newStatus: "Received",
        timestamp: daysAgo(3),
        actor: "System",
        organizerMessage: "Your booking request has been received.",
      },
      {
        previousStatus: "Received",
        newStatus: "Under Review",
        timestamp: daysAgo(1),
        actor: "Executive Assistant",
        organizerMessage: "Our team is reviewing your invitation.",
      },
    ],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },
  {
    id: "mock-2",
    reference: "DAA-7103",
    status: "Received",
    internalStatus: "New / Unassigned",
    priority: "Normal",
    assignedEa: null,
    conflictDetected: false,
    form: {
      name: "James Whitfield",
      organization: "Global Finance Summit",
      email: "j.whitfield@gfsummit.com",
      phone: "+44 7700 900123",
      timezone: "GMT (London)",
      engagementType: "Panel",
      eventTitle: "The Future of African Capital Markets",
      audienceSize: "200 – 500",
      format: "Hybrid",
      preferredDate: "2026-09-08",
      alternativeDate: "2026-09-15",
      city: "London",
      country: "United Kingdom",
      travelDetails: "Virtual participation available for panel segment.",
      budgetRange: "$10,000 – $25,000",
      recordingPermission: "Livestream",
      vipProtocol: "",
      termsAgreed: true,
    },
    documents: [],
    statusHistory: [
      {
        previousStatus: null,
        newStatus: "Received",
        timestamp: daysAgo(0),
        actor: "System",
        organizerMessage: "Your booking request has been received.",
      },
    ],
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    id: "mock-3",
    reference: "DAA-5621",
    status: "Information Required",
    internalStatus: "Awaiting Organizer Information",
    priority: "High",
    assignedEa: "David K.",
    conflictDetected: false,
    form: {
      name: "Fatima Al-Rashid",
      organization: "Dubai Leadership Institute",
      email: "fatima@dli.ae",
      phone: "+971 50 123 4567",
      timezone: "GST (Gulf)",
      engagementType: "Workshop",
      eventTitle: "Executive Presence Masterclass",
      audienceSize: "50 – 200",
      format: "In-person",
      preferredDate: "2026-10-20",
      alternativeDate: "",
      city: "Dubai",
      country: "UAE",
      travelDetails: "Business class travel and 5-star accommodation.",
      budgetRange: "$50,000+",
      recordingPermission: "No recording",
      vipProtocol: "Royal family advisory board attendance expected.",
      termsAgreed: true,
    },
    documents: [],
    statusHistory: [
      {
        previousStatus: null,
        newStatus: "Received",
        timestamp: daysAgo(5),
        actor: "System",
      },
      {
        previousStatus: "Received",
        newStatus: "Under Review",
        timestamp: daysAgo(4),
        actor: "Executive Assistant",
      },
      {
        previousStatus: "Under Review",
        newStatus: "Information Required",
        timestamp: daysAgo(2),
        actor: "Executive Assistant",
        organizerMessage: "Please provide the final agenda and venue address.",
      },
    ],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
  },
  {
    id: "mock-4",
    reference: "DAA-3387",
    status: "Confirmed",
    internalStatus: "Confirmed",
    priority: "VIP",
    assignedEa: "Sarah M.",
    conflictDetected: false,
    form: {
      name: "Dr. Ngozi Eze",
      organization: "African Union Youth Assembly",
      email: "ngoze@au-youth.org",
      phone: "+251 91 234 5678",
      timezone: "EAT (East Africa)",
      engagementType: "Keynote",
      eventTitle: "Youth Leadership & Nation Building",
      audienceSize: "1,000 – 5,000",
      format: "In-person",
      preferredDate: "2026-08-12",
      alternativeDate: "",
      city: "Addis Ababa",
      country: "Ethiopia",
      travelDetails: "Official AU travel protocol. VIP lounge access.",
      budgetRange: "$25,000 – $50,000",
      recordingPermission: "Video recording",
      vipProtocol: "Heads of state in attendance. Full security detail.",
      termsAgreed: true,
    },
    documents: [
      {
        id: "doc-2",
        name: "AU_Youth_Summit_Agenda.pdf",
        uploadedAt: daysAgo(10),
        category: "Agenda",
      },
    ],
    statusHistory: [
      {
        previousStatus: null,
        newStatus: "Received",
        timestamp: daysAgo(14),
        actor: "System",
      },
      {
        previousStatus: "Under Review",
        newStatus: "Confirmed",
        timestamp: daysAgo(7),
        actor: "Super Admin",
        organizerMessage: "Your engagement has been confirmed.",
      },
    ],
    createdAt: daysAgo(14),
    updatedAt: daysAgo(7),
  },
  {
    id: "mock-5",
    reference: "DAA-1944",
    status: "Under Review",
    internalStatus: "Awaiting Executive Review",
    priority: "Normal",
    assignedEa: "David K.",
    conflictDetected: true,
    form: {
      name: "Michael Chen",
      organization: "Singapore Management University",
      email: "m.chen@smu.edu.sg",
      phone: "+65 9123 4567",
      timezone: "Other",
      engagementType: "Advisory",
      eventTitle: "Corporate Governance Advisory Session",
      audienceSize: "Under 50",
      format: "Virtual",
      preferredDate: "2026-08-12",
      alternativeDate: "2026-08-19",
      city: "Singapore",
      country: "Singapore",
      travelDetails: "Virtual only — no travel required.",
      budgetRange: "$5,000 – $10,000",
      recordingPermission: "Audio only",
      vipProtocol: "",
      termsAgreed: true,
    },
    documents: [],
    statusHistory: [
      {
        previousStatus: null,
        newStatus: "Received",
        timestamp: daysAgo(2),
        actor: "System",
      },
      {
        previousStatus: "Received",
        newStatus: "Under Review",
        timestamp: daysAgo(1),
        actor: "Executive Assistant",
        organizerMessage: "Schedule conflict detected — under executive review.",
      },
    ],
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
];

export function getMockBookingRequests(): BookingRequest[] {
  return MOCK_BOOKING_REQUESTS;
}
